ryanisaacg/quicksilver

src/graphics/atlas.rs

Previously a parallel vector of regions to images was maintained, but now each region just tracks with image it takes from so they can be stored in a single flat array

Reduced the number of allocations performed when loading an atlas

---

src/lib.rs

Previously it lacked a call to mem::forget, which meant that the Vec was deallocated as soon as the function exited

Fixed the allocate_memory function freeing the memory

---

src/input/gamepad/gamepad.rs
src/input/gamepad/manager.rs

Currently gilrs doesn't support macOS and will just panic if called.
The workaround is to maintain the outward API of Gamepad and GamepadManager
but to just return nothing when they are queried.

Mocked out game controller input on macOS

---

src/graphics/backend.rs

The backend wasn't clearing its vertex list, so drawing the same triangles with different positions
would produce the original set of triangles, causing the illusion the screen wasn't refreshing at all.
Resolves #160

Fixed bug in the backend that prevented screen refreshes

---

appveyor.yml

These targets are already built for macOS and Linux on Travis, but because appveyor takes longer

Removed beta and nightly targets from appveyor

---

src/graphics/surface.rs

It was calling window.backend.flush, much of the work of which has now been moved to the higher-
level window.flush

Fixed the bug where Surface didn't capture render_to

---

.travis.yml

Beta is sufficient to know of changes coming down the pike that need to be addressed,
nightly testing is far more likely to catch regressions in the Rust compiler than actual issues.

Nightly failures should no longer trigger a full build failure

---

src/ffi/wasm.rs

The get_image_width and get_image_height functions should return unsigned numbers

Fixed the WASM FFI types not matching the Quicksilver types

---

src/graphics/window.rs
src/input/event.rs

If they aren't projected, the user gets a raw mouse coordinate that ignores the letterboxing
of the window.
Resolves #209

Projected the mouse coordinates in the MouseMoved event

---

src/input/button_state.rs
src/state.rs

Fixed the input state not being cleared from the just-updated state in WASM

---

docs/index.html

The draw-geometry example text was written out twice, but one was actually a link
to the font example. The text on the font example link now describes it correctly.

Fix the description of the font example

---

CHANGES.md
src/graphics/font.rs

This adds simple methods to create Font instance with static lifetimes from raw bytes.
I didn't want to introduce lifetime dependency, but I'd like to have option to embed fonts into binary and use it instead of runtime loading
Hope you don't mind it

Add initialization from bytes for Font

---

src/input/event.rs

Glutin reports minimized windows as having been resized to (0, 0). This breaks the scaled resize code and therefore leaves the viewport as zero-sized for the rest of the application's runtime.
Resolves #249

Fix bug where minimizing the window clears content

---

src/graphics/vertex.rs

Instead of calling unwrap on the PartialOrd which is known to always return Some, it is better to wrap an Ord in a Some for the impl of PartialOrd
Makes progress on #234

Remove a possible panic from the Vertex Ord impl

---

examples/font.rs
examples/image.rs
examples/sound.rs
src/asset.rs
src/lib.rs

It automtaes away polling and updating an enum state, and also obviates the need to actually store the Futures involved. It even eliminates the need to name or understand the futures, as the Asset manages that for you.

Add Asset to help manage loading futures

---

src/lib.rs

The functions for CString allocation that were necessary for the JS bridge weren't marked as unused because they were public, but with stdweb they are dead code.
Resolves #265

Remove dead functions from lib.rs

---

CHANGES.md
examples/draw-geometry.rs
src/geom/mod.rs
src/geom/objects/line.rs
src/geom/objects/mod.rs
src/geom/objects/triangle.rs
src/geom/vector.rs

Hi again.
As I already mentioned in a comment below #279, I hereby implemented the line drawing functionality with some additional features.
These are:
- Point/Line collision
- Line/Line collision
- Line/Rectangle collision
- Line/Circle collision
- a `distance` method for `Vector`
- Lines now have a standard thickness which can be overridden by using `with_thickness`
- thanks to the new `DrawAttributes`, `Line`s can also be transformed now. Thanks again for that!
Things that are still missing:
- more objects (triangles, quadrilaterals, basically any polygons I'm still working on, this includes an overhauled circle) but I wanted to at least restore line drawing
- `Line` does not support the `constrain` method because I honestly have no idea what it does
- does it fit the object to be in …

Reimplement Line drawing, implement Triangle object

---

CHANGES.md
examples/font.rs
examples/sound.rs
src/lib.rs

Re-export the futures::future module as `combinators`
This allows users to build complex futures for the `Asset` struct without needing to worry about including `futures` as a dependency or the ongoing effort to get futures into libstd.
**Testing**

Re-export the relevant portions of the Futures API

---

Cargo.toml
src/file.rs

This allows use of the new XmlHttpRequest type. It's an entirely internal change, but it does decrease use of `js!` within the library, which is always a plus.
Resolves #319

Bump to stdweb 0.4.8

---

CHANGES.md
examples/draw-geometry.rs
examples/font.rs
examples/image.rs
examples/pulsing-circle.rs
examples/raycast.rs
examples/rgb-triangle.rs
examples/sound.rs
src/geom/circle.rs
src/geom/objects/line.rs
src/geom/objects/triangle.rs
src/geom/rectangle.rs
src/geom/shape.rs
src/geom/vector.rs
src/graphics/color.rs
src/graphics/drawable.rs
src/graphics/image.rs
src/graphics/immi.rs
src/graphics/mesh.rs
src/graphics/mod.rs
src/graphics/window.rs
src/lib.rs

This allows for storing rendered Vertex and GpuTriangle lists without
the overhead of a framebuffer.
This will allow a much more flexible draw API, which is half of addressing #315.
**Testing**

 Add a Mesh structure and a RenderTarget trait

---

CHANGES.md
examples/font.rs
examples/image.rs
examples/sound.rs
src/geom/circle.rs
src/geom/mod.rs
src/geom/objects/line.rs
src/geom/objects/triangle.rs
src/geom/positioned.rs
src/geom/rectangle.rs
src/geom/shape.rs
src/geom/tilemap.rs
src/geom/vector.rs
src/graphics/atlas.rs
src/graphics/drawable.rs

Shape being an enum means there is rampant code duplication, even though
it does allow storing different shapes in the same memory location.
Making Positioned a part of Shape allows for one enum to contain all
general shape behavior, making writing truly generic Shape code much
more achievable
Resolves #264
**Testing**

Make Shape a trait instead of an enum

---

CHANGES.md
README.md
examples/draw-geometry.rs
examples/font.rs
examples/image.rs
examples/lyon.rs
examples/raycast.rs
examples/rgb-triangle.rs
examples/sound.rs
src/graphics/window.rs
src/lib.rs
src/state.rs

The Window will now automatically present
The correct behavior is that the Window calls present exactly once, at
the end of each draw frame. It would be easier and reduce error
possibility if Quicksilver handled this automatically, especially as
present does unexpected things on the web.
**Testing**

Remove the present function

---

src/lifecycle/state.rs

The web target currently doesn't produce the message that caused a
panic, making error handling hard or impossible.
It will help diagnose #343 

Log errors before panicking on web

---

src/graphics/backend/webgl.rs

The texture loading was using the wrong overload, causing the webgl
context to expect a PBO. Using the correct overload resolves this.
Resolves #348 

Fix web texture loading failing

---

src/sound.rs

The WASM sound bindings have apparently been broken since the stdweb port.
Resolves #349 

Fix loading and simultaneous sound playing

---

src/lifecycle/settings.rs

1 / 60 is the number of frames per *second*, not per *millisecond.* This made the update loop quite a bit broken.

Fix the default tick rate

---

src/graphics/image.rs

Tetxure subimages weren't actually taking fragments of images, which is a problem.
Resolves #363 

Fix texture subimages

---

src/lib.rs
src/lifecycle/asset.rs

There's no need to export Async because the end users can just build futures out of combinators, and shouldn't poll directly.

Remove unnecessary export of Async

---

CHANGES.md
src/lifecycle/event.rs

This fixes the MouseWheel event on non-wasm platforms. It seems to have been copied from MouseMove.
The MouseWheel event didn't work.

Fix MouseWheel Event

---

CHANGES.md
src/file.rs

There's a bug at the test of examples/font.rs for the target wasm32-unknown-unknown on chromium version 69.0.3497.81 (it fails to load the asset and generates uncaught panic).
It was due to the load_file function in file.rs only check the status code of the xhr request. The status code does not guarantee the xhr request is finished, but the readyState does.

check xhr ready_state to fix 'Asset' bug on chromium

---

CHANGES.md
src/backend/gl3.rs
src/backend/webgl.rs

If you draw something (semi-)transparent on top of something that is
opaque, the framebuffer used to store a (semi-)transparent pixel
afterwards, even though the color below was entirely opaque. This commit
fixes the blend function in order to calculate the expected opacity for
the framebuffer.

Fix Alpha Blending

---

CHANGES.md
src/geom/shape.rs

I encountered a bug in `Rectangle::contains`.
```rust
fn contains(&self, point: impl Into<Vector>) -> bool {
let p = point.into();
return p.x >= self.x()
&& p.y >= self.y()
&& p.x < self.x() + self.width()
&& p.y < self.y() + self.width() // Notice that width is used instead of the height
}
```
```rust
fn contains(&self, point: impl Into<Vector>) -> bool {
let p = point.into();
return p.x >= self.x()
&& p.y >= self.y()
&& p.x < self.x() + self.width()
&& p.y < self.y() + self.height() // Fixed
}
```

Fix bug in `Rectangle::contains`

---

src/graphics/resize.rs

Integer scaling was only working for scaling larger than the provided resolution, this allows it to work smaller also,

Fix a bug in integer scaling resize method

---

CHANGES.md
src/lifecycle/run.rs

Web key input works on the basis of lookup in a table that maps from the
web key strings to the Quicksilver key values. A test is included to
ensure this does not happen in the future.
Resolves #425 

Fix the key input on the web

---

CHANGES.md
src/lifecycle/run.rs

Pointer events report for both touch input and mouse input, so using
pointer events instead of mouse events gets this for "free."
Resolves #366 

Add touch input support for web

---

CHANGES.md
src/saving.rs

On the web, the load implementation read from a different kind of storage than
save, which caused save and load to fail.
Resolves #437 

Fix docs and implementation of save and load

---

CHANGES.md
examples/font.rs
src/lifecycle/event.rs
src/lifecycle/run.rs

Typed allows reading alphanumeric characters from text input. This
allows easy creation of text editing widgets without having to convert
from key codes.
Resolves #435 

Add a Typed event variant

---

.gitignore
src/graphics/immi.rs

This PR updates the matrix_to_trans() function in immi.rs to correctly translate the immi Matrix to a Quicksilver Transform.  This fix an issue with immi Alignment not working and as a consequence the image9 widget as well.  I was unable to figure out how to get the transform variable in draw_triangle to account for the screen being inverted.  The Alignment::top() would put the image at the bottom of the screen when there was a Transform::scale(1,-1) in the calculation.  As a fix I just inverted the y value of the uv coordinates, this seems to work.
https://github.com/ryanisaacg/quicksilver/issues/431

Immi transform fix

---

CHANGES.md
Cargo.toml
src/saving.rs

Support raw bytes saving with save_raw/load_raw
save_raw take &[u8] and load_raw return Vec<u8>
in wasm, bytes will be encoded with base64 bacause LocalStorage only accept string
Current quicksilver only support saving via serde_json
it's good but sometime I want to saving raw bytes
like using other Serializer or encrypt save data as is

Support raw bytes saving

---

CHANGES.md
src/lifecycle.rs
src/lifecycle/application.rs
src/lifecycle/run.rs

New pull request which branches off development instead of master.
This resolves issue #446.
My main concern is that the State trait is forced to be the one and only global state and there is no way to work around it, making it more difficult to integrate quicksilver in existing projects and environments. This change allows custom initialisation of the global state, exposing it to the world outside of it. 

Added a run_with function that allows custom state initialisation

---

CHANGES.md
src/graphics/font.rs

Rusttype can produce negative minimum bounds as well as sizes greater
than the specified font size.
In the former case, we would get an overflow:
thread 'main' panicked at 'attempt to add with overflow'
In the latter an out-of-bounds check trying to write to the `pixels`
Vec:
thread 'main' panicked at 'index out of bounds: the len is 20736 but the index is 20884'
It's not clear what exactly is causing this, but it can be triggered by
a combination of a specific text and font.
This commit adds bounds checks to handle both cases. Similar checks can
be found in the rusttype example:
https://gitlab.redox-os.org/redox-os/rusttype/blob/1846aae84d1a60b493bf3d55fd41a76367f7f787/examples/simple.rs#L60-61
I was trying to render text and kept getting panics under certain circumstances.
See my repro …

Font bounds

---

CHANGES.md
examples/font.rs
src/graphics/font.rs

This extends the `Font::render` method to handle string slices
containing line breaks (`\n`).
Fixes #457
The fact that `Font::render` only handles single-line strings can come as a surprise to newcomers and there's no obvious way to as a user of the library. Splitting the strings at the call site produces one `Image` text per line, which complicates the storage as well as how to apply transforms to it.
Calling `font.render("First line\nSecond line\nThird line", &style)` (see the `fonts` example) produces:
(ignore the image quality -- that's due to my system's DPI clashing with the default image scale strategy)
This is either a new feature or a bug fix depending on one's …

Add multiline text rendering

---

CHANGES.md
Cargo.toml

Bumped nalgebra to ^0.17, ncollide to ^0.18. The library updates are breaking, but I've decided to not mark this change as such, as the API didn't require changes, and dependencies in question are optional.
Recent releases of nalgebra, ncollide, and nphysics are not immediately compatible with versions quicksilver depends on - for example, attempting to convert a 0.17 `Matrix3` to `Transform` (which expects a 0.16 `Matrix3`) may yield bewildering erros:
```
error[E0277]: the trait bound `quicksilver::geom::Transform: std::convert::From<nalgebra::Matrix<f32, nalgebra::U3, nalgebra::U3, nalgebra::ArrayStorage<f32, nalgebra::U3, nalgebra::U3>>>` is not satisfied
--> src\main.rs:307:62
|
307 |                 .map(|body| body.position().to_homogeneous().into())
| …
```

nalgebra and ncollide2d version bump

---

src/graphics/atlas.rs

Skipping empty lines at the beginning of atlas file.
There was a problem loading an atlas when the definition file had empty lines at the beginning (e.g. when created using [gdx-texture-packer-gui](https://github.com/crashinvaders/gdx-texture-packer-gui))
- Bug fix

Skipping empty lines at the beginning of atlas file.

---

CHANGES.md
src/graphics/color.rs

I added two functions to instantiate colors from an HEX value (e.g. "#FFFFFF" or "333") and from and RGBA value (e.g. 255, 243, 255, 1.0).
While trying to write a game protoype, I wanted to try different palettes and colors, but mapping the 0-255 value to 0-1 slowed down the process. Thus, this little improvement.

Add color creation from rgb and hex values

---

CHANGES.md
examples/lyon.rs
src/graphics/lyon.rs

Added support for lyon's [`StrokeTessellator`](https://docs.rs/lyon_tessellation/0.13.1/lyon_tessellation/struct.StrokeTessellator.html), allowing to use it to tesselate paths as strokes as opposed to filled shapes you get with [`FillTessellator`](https://docs.rs/lyon_tessellation/0.13.1/lyon_tessellation/struct.FillTessellator.html).
Expanded the lyon example to support stroke tessellation.
Currently, there's no way to use [`StrokeTessellator`](https://docs.rs/lyon_tessellation/0.13.1/lyon_tessellation/struct.StrokeTessellator.html) within quicksilver.

Add support for lyon's StrokeTessellator

---

CHANGES.md
src/saving.rs

This commit adds a running doctest that round-trips a structure.
It particularly calls out the fact that you need to specify the
generic type for the `load` function.
When I first tried to use the `save` and `load` functions I got a non-obvious error from Serde, complaining about finding a map when it expected `()`. The reason was that I had forgotten the generic type parameter on the `load` method. It's a newbie sort of error, but very easy to make - the iterator `collect` method has exactly the same issue. It's nice to see a fully round-tripping example.
- Bug fix (documentation only, there is no code change)

Improve documentation for load and save functions.

---

src/tutorials/_03_input.rs

Fixes a typo in the tutorial.
It looks like lines got accidentally reordered.
- Doc fix

fix out of order line in input tutorial

---

README.md
src/lib.rs

The main doc page (in `lib.rs`) had a couple of issues that hurt Quicksilver's presentation. There were linebreaks missing which caused some links to break and `//!` to appear in the middle of lines (see #503). Also, the logo link targeted a nonexistent file.
**Before**
**After**
- Bug fix

Fix broken formatting in documentation

---

CHANGES.md
src/geom/shape.rs

Added `transform_bounding_box` to `Shape`. This allows you to first transform a shape then get a bounding box based on the transformed shape.
Transforming a shape with `draw_ex` happens at the very end of your game logic. If you are performing logic on a shape, such as collision detection, you end up performing the the logic on the un-transformed shape's bounding box which can lead to unexpected game play.
Resolves #513 
This issue was just about rotating a bounding box but as I was implementing the change I thought it would be a good idea to cover all transformations (scale, rotate, translate) instead of just rotate.

Add `transform_bounding_box` to Shape

---

src/graphics/drawable.rs

Thanks for the great library! This is a fix for projecting background images into circles. The image should be projected into the bounding box of the `CIRCLE_POINTS`, not of `self`. 
- Before
-After

Fix projection for Circle Background::Img

---

src/graphics/drawable.rs

While trying out release 0.3.17, I noticed there was an mistake in my PR 520, the change was applied to `impl Drawable` for `Triangle` instead of `Circle`.
Hotfix for a recently introduced bug.
See PR 520

Apply modification to the correct impl Drawable

---

Cargo.toml
README.md
src/backend/webgl.rs

- Added a feature for using webgl1 instead of webgl2 (the default on the wasm32-unknown-unknown target).
- When using webgl1, request the `OES_element_index_uint` extension so that we can use u32s as our indices.
- There is a case to be made that, instead, the index array could be templated or otherwise made into a u16 array but this seemed much less intrusive for a first time contributor.
- Also, that extension has very good adoption. https://webglstats.com/webgl/extension/OES_element_index_uint
- Removed the only webgl2 specific call as, in the context of the default shader, it doesn't do anything.
This is motivated by Safari's absolutely abysmal WebGL2 support. That and that QuickSilver's rendering API is largely (entirely???) compatible with WebGL1.
No screenshots but I did check each …

Add WebGL1 as an optional rendering context

---

CHANGES.md
Cargo.toml
src/graphics/image.rs

Also update image to 0.22 from 0.21, and remove the jpeg rayon feature.
This may take some perf hit on desktop, but it removes unnecessary
complexity and makes jpeg work on web.
Now that image isn't depended on by winit, there's no other crate
toggling on default features accidentally. Removing the rayon feature
actually removes it!
See discussion of image formats in #552 
Resolves #508

Restrict image formats to png and jpeg

---

CHANGES.md
src/graphics.rs

The Default::default of an Option is None, which disables blending. That
line was supposed to enable the default blending mode in golem, which is
a sensible blending default, instead of disabling blending entirely.
See https://github.com/ryanisaacg/quicksilver/issues/552#issuecomment-571897087

Fix the default blending

---

Cargo.toml

Restricting the formats available in "image" upstream dependency to get images loading in WASM builds. This is a **PARTIAL FIX TO 0.3.22 - APPEARS TO WORK FOR PNG BUT NOT JPEG**
Changed the following line in Cargo.toml:
`
image = { version = "0.21", default-features = false, features = ["png_codec", "jpeg"] }
`
Images displayed on different native platforms. Image display crashes out WASM on Chrome and Firefox (Mac and Windows)
I attempted bumping image->0.22 but without happiness. This is a backport fix so not putting more effort as we look forward to 0.4.

Backport image WASM fix to 0.3 branch (Works for PNG only in my tests)

---

CHANGES.md
src/geom/vector.rs

Implementation of the std::iter::Sum trait for iterators of Vectors.
Closes #573.

Sum for Vectors

---

CHANGES.md
src/timer.rs

Thanks to #609 I noticed that I made a mistake with the order of subtraction in the Timer::remaining method.
I also added the Timer::period method as a way to get the time between ticks so you don't have to calculate that yourself when you use Timer::time_per_second
It solves #609

Fix Timer::remaining not doing what it promisses

---

README.md

I have updated Mergui to work with 0.4, though those versions are still listed as alpha (latest version is https://crates.io/crates/mergui/0.1.0-alpha0.3 ). When working on Mergui, this is the version that gets my attention.
This means that the 0.3 compatible version of Mergui is pretty much dead. The only exception is if someone wants to use it and finds a bug preventing them from doing so. In that case, I am willing to discuss on how to best move forward to get a new version out that fixes said bug.
Because of this, I decided to let Mergui stay in the list for 0.3 and put it in the list for 0.4 as well. Feel free to either remove it from the 0.3 list or give it another name/description to make this clear

Put mergui in the correct version

---

CHANGES.md
Cargo.toml
src/geom/circle.rs
src/geom/rectangle.rs
src/geom/vector.rs

I discovered that Rectangle, Vector and Circle can't be (de)serialized even with the `saving` feature enabled. This PR adds this functionality.
In my case I need it to more easily send the shapes from 1 system to another, however I would guess that this makes saving playerdata easier, which is why I added it to the saving feature rather than make a new one.
I also didn't add it to triangle/line as those are deprecated.

Add serde support if saving is enabled

---

CHANGES.md
src/graphics/font.rs

Having failed to reproduce the font failing to show up on screen in #607, I think the bug is this one-line fix. The extents didn't take into account the last line of text, so it would report 0 height for a single line.
Resolves  #607 
Resolves #633

Fix text extents not reflecting line height

---

CHANGES.md
examples/04_render_to_texture.rs
examples/08_input.rs
examples/10_resize.rs
src/graphics.rs
src/graphics/resize_handler.rs
src/run.rs

Setting the viewport yourself could be useful in relatively niche cases (picture-in-picture, split-screen rendering) but it mostly introduces various ways to shoot yourself in the foot. Instead, it's best to focus on setting the projection, and make setting the projection very easy. 
`Graphics::set_viewport` has been removed, as has `fit_to_surface` and `fit_to_window`. `Graphics::flush` has been split into two functions, `flush_surface` and `flush_window` to handle setting the viewport. 
Setting the projection introduces the same problem. `set_projection` has been removed, and `ResizeHandlers` have been integrated into the automatic viewport handling. Projection is now set automatically when rendering to the Window or the Surface, and the Surface-coordinate-space issue OpenGL introduces …

Remove the manual viewport API

---

CHANGES.md
src/graphics.rs

This was causing images to be destructed before they hit the shader. 
Resolves #601

Don't allow images to drop while they're in-flight

---

src/graphics.rs

Commit bcb33de3 added two `dbg!` calls into graphics.rs which make the console output rather noisy and I assume were unintentional. This simply removes them.

Remove stry dbg! calls

---

CHANGES.md
src/timer.rs

This adds a `#[derive(Debug, Clone)]` onto the `Timer` struct, thus allowing it be displayed in debug print statements and allow creating copies of it.
Resolves #645 
I assume this doesn't count as breaking? I'm not 100% used to semver.
Checked the documentation and it was correct.

Derive Debug and Clone for Timer

---

CHANGES.md
src/graphics.rs

`screen_to_camera` should take into account what `set_view` is doing.
Resolve #647

Unproject the view in screen_to_camera conversion
