ryanisaacg/quicksilver

examples/wasm.rs, src/input/mouse.rs
=> Wrapped all mouse members in functions wrather than direct access

src/asset.rs, src/geom/circ.rs, src/geom/line.rs, src/geom/mod.rs, src/geom/rect.rs, src/geom/shape.rs, src/geom/util.rs, src/geom/vector.rs, src/graphics/color.rs, src/graphics/image.rs, src/graphics/mod.rs, src/graphics/window.rs, src/input/key.rs, src/input/mod.rs, src/input/state.rs, src/input/viewport.rs, src/lib.rs, src/sound.rs
Also added a configuration to deny undocumented public members
=> Documented each public member of the library

html/script.js, src/graphics/resize.rs, src/graphics/window.rs
=> [WIP] Add configurations to the Window struct

examples/surface.rs, html/script.js, src/gl/desktop.rs, src/gl/wasm.rs, src/graphics/backend.rs, src/graphics/canvas.rs, src/graphics/image.rs, src/graphics/mod.rs, src/screen.rs
Currently render-to-texture works except if you don't draw a texture to the web backend. Binding a dummy texture might fix this.
=> Render to texture

README.md, bridge.js, examples/basic.rs, examples/draw-geometry.rs, examples/pulsing-circle.rs, src/ffi/wasm.rs, src/lib.rs, src/state.rs
This means the functions get typechecked without having to instantiate the macro. Also, the user gets to see the main function.
=> Switched from a run macro to a run function

.travis.yml
=> Add mac travis targets

bridge.js
=> Added a definition for roundf in the WASM bridge

Cargo.toml, examples/image.rs
=> Created an example of loading an image and displaying it to the screen

src/lib.rs
=> Re-exported the Future and Async types from futures

src/geom/tilemap.rs
This has a pretty large performance cost but has a large correctness benefit, so I'm not sure that physics-heavy code should be implemented in quicksilver going forward.
=> Fix tilemap bug

bridge.js, src/ffi/wasm.rs, src/lib.rs, src/state.rs
=> Fix the WASM initialization failing

examples/draw-geometry.rs, examples/font.rs, examples/image.rs, examples/platformer.rs, examples/pulsing-circle.rs, examples/sound.rs, src/graphics/drawable.rs, src/graphics/mod.rs
Generally sprites would contain at least animations, but possibly also scene graphs
=> Renamed Sprite to Draw because Sprite has other implications

src/error.rs, src/graphics/atlas.rs, src/graphics/image.rs, src/graphics/vertex.rs, src/input/gamepad.rs, src/sound.rs
=> Added #[doc(hidden)] to non-user-facing impls

src/ffi/wasm.rs, src/file.rs, src/graphics/image.rs, src/sound.rs
=> Fixed a few import issues with WASM

src/lib.rs
=> Added the html_root_url attribute to the crate

Cargo.toml
The website isn't currently live, but it will be before the next crates.io release
Makes progress on #184
=> Added a link to the repository's website

src/graphics/font.rs, src/graphics/image.rs, src/graphics/surface.rs
There is no reason to make negative image sizes representable
Makes progress on #184
=> Made the image size unsigned instead of signed

CHANGES.md
=> Created a changelog for the upcoming v0.2.0 release

README.md, src/lib.rs
Deployment is now much better explained in the README
=> Fixed and updated the README

src/graphics/drawable.rs
=> Made the transform of circles relative to their centers

Cargo.toml, docs/bridge.js, src/input/event.rs, src/input/key.rs
=> Bumped glutin to version 0.16

CHANGES.md, Cargo.toml, README.md
- sebcrozet added official wasm32 support for nalgebra and updated their deps in all three crates
- adding deps.rs badge for a visual indicator
=> Bump deps and add deps.rs badge to readme

CONTRIBUTING.md
=> Add a CONTRIBUTING file to the project

src/error.rs, src/saving.rs
=> Add an error type specific to saving and loading

CHANGES.md, examples/font.rs, src/graphics/font.rs, src/graphics/mod.rs
=> Make the font styling a standalone structure

CHANGES.md, examples/draw-geometry.rs, src/graphics/drawable.rs
Remember when you said, that there's no line tool in quicksilver? Now there is.
I hope this is the most performant way to do this.
Also, first real pull request! 😄 
EDIT: Dammit, I forgot the CHANGES.md... on it!
EDIT²: I just noticed, that Clion automatically applied a small cleanup, I hope thats okay. Whats wrong with rustfmt anyway?
=> Add a line drawing tool

examples/draw-geometry.rs, examples/font.rs, examples/image.rs, examples/pulsing-circle.rs, examples/raycast.rs, examples/sound.rs, src/graphics/backend/gl3.rs, src/graphics/backend/mod.rs, src/graphics/backend/webgl.rs, src/graphics/font.rs, src/graphics/image.rs, src/graphics/surface.rs, src/graphics/window.rs, src/lib.rs, src/state.rs
=> Convert the backend error handling to bubble errors where possible

src/state.rs
=> Fix possible bug where multiple frames could report an input was changed

src/error.rs, src/graphics/window.rs, src/input/gamepad.rs
=> Add gilrs error bubbling

src/graphics/atlas.rs
=> Remove 'unwrap' from the Atlas loading code

CHANGES.md, examples/draw-geometry.rs, examples/font.rs, examples/image.rs, examples/pulsing-circle.rs, examples/sound.rs, src/geom/circle.rs, src/geom/mod.rs, src/geom/objects/line.rs, src/geom/objects/mod.rs, src/geom/objects/triangle.rs, src/geom/rectangle.rs, src/geom/shape.rs, src/geom/transform.rs, src/geom/vector.rs, src/graphics/drawable.rs, src/graphics/image.rs, src/graphics/mod.rs, src/graphics/view.rs, src/graphics/window.rs, src/lib.rs
=> Create a new more convenient draw interface

Cargo.toml, src/error.rs, src/geom/transform.rs, src/graphics/atlas.rs, src/graphics/backend/gl3.rs, src/graphics/backend/webgl.rs, src/graphics/font.rs, src/graphics/image.rs, src/input/gamepad.rs, src/input/mouse.rs, src/lib.rs, src/saving.rs, src/sound.rs
Enable some lints that will generally increase code quality.
Resolves #300
**Testing**
=> Enable a few new lints

CHANGES.md, src/geom/circle.rs, src/geom/objects/line.rs, src/geom/objects/triangle.rs, src/geom/rectangle.rs, src/geom/shape.rs, src/geom/tilemap.rs, src/geom/transform.rs, src/geom/vector.rs, src/input/button_state.rs
Add #[must_use] to a few functions in the library
Most functions without side effects should be marked #[must_use]
Resolves #286
**Testing**
=> Add must_use to relevant functions

CHANGES.md, README.md, examples/basic.rs, examples/draw-geometry.rs, examples/font.rs, examples/image.rs, examples/pulsing-circle.rs, examples/raycast.rs, examples/rgb-triangle.rs, examples/sound.rs, src/file.rs, src/geom/tilemap.rs, src/lib.rs, src/saving.rs, src/sound.rs, src/state.rs
Also add an optional function to State that allows for custom error
logging, which should make debugging on WASM much easier.
This means that, barring bugs in Quicksilver, no normal API usage should cause a panic.
Resolves #234 
**Testing**
=> Remove the remaining uses of unwrap

Cargo.toml, src/sound.rs
=> Bump rodio to 0.8.0

README.md, src/graphics/backend/gl3.rs, src/graphics/backend/mod.rs, src/graphics/backend/webgl.rs, src/graphics/window.rs, src/lib.rs, src/state.rs
There's no real advantage to finding the canvas, but creating it is more
convenient and involves less interaction with the DOM global state.
This PR has the wasm backend create a canvas node and add it to the document, meaning you don't have to worry about providing one in your index.
This means that `cargo web start` will work out-of-the-box.
**Testing**
=> Create a canvas instead of trying to find one

src/lifecycle/application.rs
=> Fix projects not drawing by default

.travis.yml, Cargo.toml, src/lib.rs, src/lifecycle/gamepad_provider.rs
Fix the compile issues when the default features are enabled, and add travis build targets to prevent it from happening again.
Resolves #338 
**Testing**
=> Fix default features

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, PULL_REQUEST_TEMPLATE.md
They were too verbose and noisy; hopefully fixing this will encourage
contributors to actually use them.
=> Simplify the issue and PR templates

src/file.rs
On my machine, HTTP responses were being handled as `ArrayBuffer` instead of `TypedArray<u8>`. This change modifies the file loading to handle both.
This fixes the errors in #343, but the examples still don't work as expected.
I get a black box on the image example, as well as the following console warnings (some probably relevant):
> Error: WebGL warning: drawElements: This operation requires zeroing texture data. This is slow. image.js:587:249
> Error: WebGL warning: texImage2D: Buffer for `target` is null. image.js:512:436
> Error: WebGL warning: generateMipmap: The base level of the texture is not defined. image.js:614:138
The first happens on pretty much every example, though the second two seem highly relevant. 
I didn't see any …
=> Fix file parsing by accepting ArrayBuffer

scripts/pre-commit, scripts/set-wasm, setup.sh
With a very full CI suite that's run against every PR, local testing seems unnecessary
=> Remove the commit hook scripts

CHANGES.md, src/backend/gl3.rs, src/backend/mod.rs, src/backend/webgl.rs, src/lifecycle/settings.rs, src/lifecycle/window.rs
=> Add multisampling AA support through Settings

Cargo.toml
This fixes the compile issues on WASM.
=> Update versions of webgl and gl-rs

src/geom/rectangle.rs
=> Fix the AABB -> Rectangle conversion

docs/index.html, index.html
This should make the website easier to find with Google.
=> Add metadata to the website

examples/raycast.rs, examples/rgb-triangle.rs, src/graphics/mesh.rs, src/tutorials/_11_mesh.rs
=> Rename Mesh::apply to Mesh::extend

CHANGES.md, src/graphics/drawable.rs, src/tutorials/_11_mesh.rs
=> Add an example to the tutorial of implementing the Drawable trait

docs/example.html
=> Add labels to the example pages

.travis.yml
Code coverage would be nice to have, and now that tarpaulin can replace kcov it should be easier and more reliable.
=> Add tarpaulin-based codecov support

CHANGES.md, src/geom/transform.rs
=> Fix the derivation of PartialEq on Transform

CHANGES.md, src/graphics/drawable.rs
Closes #406 
Using the exact same code as in #406
=> Fix bug: transformed lines not rendering properly

CHANGES.md, Cargo.toml, src/backend.rs, src/backend/gl3.rs, src/backend/webgl.rs, src/graphics/image.rs, src/lifecycle/window.rs
Resolves #268 
If users can get image data out of `Image` objects, they can build whatever screenshot system makes the most sense to them.
=> Add the ability to capture screen regions

CHANGES.md, examples/image.rs, src/backend.rs, src/backend/gl3.rs, src/backend/webgl.rs, src/graphics/image.rs, src/graphics/surface.rs, src/lifecycle/window.rs
The previous API had all sorts of misleading behavior (not respecting DPI, not being in user-space coordinates) that would make it feel out of place with the rest of the framework.
=> Fix screenshot API

.travis.yml, src/graphics/drawable.rs
This multiplicatively blends the image with the given color, allowing
white images as color masks.
Resolves #444 
=> Add a blend background option

CHANGES.md, src/graphics/immi.rs
Immi font rendering got broken by the recent immi module changes, this (somewhat) fixes it.
Resolves #456 
=> Fix font rendering with immi

CHANGES.md, src/graphics/immi.rs
Running the `immi` example, the button reacts to mouse hover but not to a button press.
=> Fix Immi mouse click handling

CHANGES.md, src/lifecycle/run.rs
=> Fix typed events and some key bindings on web

README.md
=> Updated game list.

README.md, src/backend/webgl.rs
Should fix https://github.com/ryanisaacg/quicksilver/issues/512
=> Fix hardcoded RGBA value in webgl backend create_texture

examples/rgb-triangle.rs
Use a better name in the example.
A more accurate name in the example lends authority to the quicksilver project and avoids confusing beginners.
It's essentially just a documentation change, since it updates an example.
=> Replace Image Example with Rgb Triangle Example in examples/rgb-triangle.rs

README.md
Add the game and gui library I'm working on to the readme
=> Add Mergui and Arena keeper

CHANGES.md, src/lifecycle/window.rs
Should fix #538 
@MaulingMonkey, I'm without easy access to gamepad hardware for now. Can you test this and confirms it fixes your issue?
=> Fix gamepad released

CHANGES.md, src/graphics/surface.rs
Resolves #529
This fixes a soundness hole, so it can be released as a patch release.
=> Mark surface unsafe

examples/03_rgb_triangle.rs
Adding a trivial example to get familiar with the new APIs.
Probably not quite ready, would wait for a new release of blinds (alpha9 or something?)
=> Add RGB example using Mesh

CHANGES.md, examples/05_blending.rs, src/graphics.rs
#552, this re-adds blending support (with much more flexibility than the old graphics pipeline.)
=> Add support for setting the blend mode

CHANGES.md, src/graphics.rs
=> Fix buffer capacity errors

CHANGES.md, Cargo.toml, src/lifecycle.rs
This moves to the new event API
=> Update blinds to version 0.1.0

CHANGES.md, src/lib.rs
=> Re-export libraries that appear in the public API

README.md
Two things I've been playing with:
1. quicksilver-utils-async includes the async TaskContext you've seen, and adds async sleeping, websockets, and simple http requests. My plan is to keep the scope limited to a collection of cross-platform async primitives (including re-exports of other libraries) that are known to work with major versions of quicksilver.
2. quicksilver-utils-ecs is mostly a proof-of-concept right now, but I plan to organize and evolve it into a collection of batteries-included rendering systems for sprites, effects, backgrounds, map tiles, etc as well as some sort of configurable, key-mapped input system.
=> Add my projects, and add descriptions to all libraries

CHANGES.md, Cargo.toml, src/graphics/image.rs
=> Update golem and fix warnings, docs

README.md
=> bump the version in readme

CHANGES.md, src/geom/transform.rs
I added implementations for AddAssign, SubAssign, and MulAssign for Transforms.
This makes it easier to work with Transforms in your code.
=> Mul assign transform

.github/workflows/integration.yml, CHANGES.md, Cargo.toml, src/error.rs, src/graphics.rs, src/graphics/font.rs, src/lib.rs
Fix some compile issues with fonts
Resolves #600
=> Fix font features

README.md
Add silver animation to list of libraries
=> add silver animation

README.md, src/lib.rs
Minor documentation fix. Resolves #621
=> Fix building instructions for web (resolves #621)
